blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/erclx/ai-context-stacker/discussions
    about: Please ask questions in our Discussions area instead of opening an issue.
